Substituindo valores nulos por 0 na coluna 'Avaliacao'

In [43]:
import pandas as pd

csv_tele = pd.read_csv('./telemarketing_atendimento.csv', sep=',')

csv_tele['Avaliacao'] = csv_tele['Avaliacao'].fillna(0)
display(csv_tele.head(15))

csv_tele.to_excel('./TRATADO_Telemarketing_Atendimento.xlsx',sheet_name='Atendimentos',index=False)

,ID_Atendimento,Data_Atendimento,Tipo_Atendimento,Status,Meio_Contato,Tempo_Resolucao_minutos,Avaliacao
0,1,2023-10-25 18:32:57,Suporte Técnico,Resolvido,Telefone,28.0,5.0
1,2,2023-04-21 23:10:29,Suporte Técnico,Pendente,Chat Online,16.0,2.0
2,3,2023-03-02 12:47:03,Informação,Sem Solução,WhatsApp,2.0,0.0
3,4,2024-08-25 21:27:16,Suporte Técnico,Pendente,E-mail,63.0,2.0
4,5,2024-01-11 01:49:56,Reclamação,Sem Solução,WhatsApp,39.0,0.0
5,6,2023-02-01 07:35:49,Reclamação,Sem Solução,WhatsApp,109.0,4.0
6,7,2023-02-11 08:42:57,Informação,Resolvido,Chat Online,88.0,5.0
7,8,2023-08-22 06:38:53,Reclamação,Pendente,E-mail,9.0,0.0
8,9,2024-04-08 16:35:13,Cancelamento,Encaminhado,Chat Online,38.0,0.0
9,10,2023-11-30 20:14:10,Cancelamento,Pendente,Telefone,7.0,2.0
10,11,2024-10-01 09:21:19,Suporte Técnico,Encaminhado,Telefone,70.0,2.0
11,12,2024-06-07 18:46:09,Suporte Técnico,Resolvido,WhatsApp,14.0,2.0
12,13,2024-06-02 09:38:10,Informação,Pendente,WhatsApp,22.0,4.0
13,14,2023-09-22 05:33:24,Vendas,Pendente,WhatsApp,10.0,1.0
14,15,2024-08-11 11:20:30,Reclamação,Pendente,WhatsApp,81.0,5.0

Resumindo dados pela coluna 'Status' e 'Ano'

In [27]:
import pandas as pd

csv_tele = pd.read_csv('./telemarketing_atendimento.csv', sep=',')

#Substituindo da coluna avaliacao os valores nulos por 0
csv_tele['Avaliacao'] = csv_tele['Avaliacao'].fillna(0)

#Transformando a coluna Data_Atendimento em data reconhecida pelo python
csv_tele['Data_Atendimento'] = pd.to_datetime(csv_tele['Data_Atendimento'])
csv_tele['Ano'] = csv_tele['Data_Atendimento'].dt.year

filtro = csv_tele.groupby(['Status','Ano']).size().reset_index(name='Quantidade')

display(filtro)

        Status   Ano  Quantidade
0  Encaminhado  2023        1934
1  Encaminhado  2024        1858
2     Pendente  2023        2007
3     Pendente  2024        1776
4    Resolvido  2023        1963
5    Resolvido  2024        1736
6  Sem Solução  2023        1940
7  Sem Solução  2024        1786

Resumindo dados pela coluna 'Status' , 'Ano' e 'Mes

In [37]:
import pandas as pd

csv_tele = pd.read_csv('./telemarketing_atendimento.csv', sep=',')

#Substituindo da coluna avaliacao os valores nulos por 0
csv_tele['Avaliacao'] = csv_tele['Avaliacao'].fillna(0)

#Transformando a coluna Data_Atendimento em data reconhecida pelo python
csv_tele['Data_Atendimento'] = pd.to_datetime(csv_tele['Data_Atendimento'])
csv_tele['Ano'] = csv_tele['Data_Atendimento'].dt.year
csv_tele['Mes'] = csv_tele['Data_Atendimento'].dt.month_name()

filtro = csv_tele.groupby(['Status','Ano','Mes']).size().reset_index(name='Quantidade')

display(filtro)

         Status   Ano        Mes  Quantidade
0   Encaminhado  2023      April         179
1   Encaminhado  2023     August         141
2   Encaminhado  2023   December         141
3   Encaminhado  2023   February         158
4   Encaminhado  2023    January         172
..          ...   ...        ...         ...
87  Sem Solução  2024      March         147
88  Sem Solução  2024        May         187
89  Sem Solução  2024   November         176
90  Sem Solução  2024    October         173
91  Sem Solução  2024  September         156

[92 rows x 4 columns]